import { browserSessionPersistence, onAuthStateChanged, setPersistence, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { addDoc, collection, deleteDoc, doc, getDocs, serverTimestamp, Timestamp, updateDoc } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import { auth, db } from "./firebase-client.js";
import { adminUid } from "./firebase-config.js";

const $=selector=>document.querySelector(selector);
const loginView=$('#loginView'),adminView=$('#adminView'),loginForm=$('#loginForm'),form=$('#announcementForm');
const loginStatus=$('#loginStatus'),formStatus=$('#formStatus'),list=$('#announcementList');
let records=[];

function setStatus(element,message,type=''){element.textContent=message;element.className=`status ${type}`.trim()}
function toDate(value){if(value?.toDate)return value.toDate();const d=new Date(value);return Number.isNaN(d.getTime())?new Date(0):d}
function dateInput(value){const d=toDate(value);if(!d.getTime())return new Date().toISOString().slice(0,10);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function validImages(value){const lines=value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(lines.length>10)throw new Error('每篇公告最多可放 10 張圖片。');for(const line of lines){let url;try{url=new URL(line)}catch{throw new Error(`圖片網址格式錯誤：${line}`)}if(!['http:','https:'].includes(url.protocol))throw new Error('圖片網址必須使用 http:// 或 https://。')}return lines}
function resetForm(){form.reset();$('#docId').value='';$('#publishedAt').value=new Date().toISOString().slice(0,10);$('#formTitle').textContent='新增公告';$('#deleteBtn').hidden=true;setStatus(formStatus,'')}
function fillForm(record){$('#docId').value=record.id;$('#category').value=record.category||'公告';$('#publishedAt').value=dateInput(record.publishedAt);$('#title').value=record.title||'';$('#excerpt').value=record.excerpt||'';$('#content').value=record.content||'';$('#images').value=(record.images||[]).join('\n');$('#published').checked=Boolean(record.published);$('#pinned').checked=Boolean(record.pinned);$('#formTitle').textContent='編輯公告';$('#deleteBtn').hidden=false;setStatus(formStatus,'');scrollTo({top:0,behavior:'smooth'})}
function renderList(){if(!records.length){list.innerHTML='<p class="muted">尚無公告，請從左側新增第一篇。</p>';return}list.innerHTML='';records.forEach(record=>{const item=document.createElement('article');item.className='admin-item';item.tabIndex=0;const text=document.createElement('div');const title=document.createElement('h3');title.textContent=record.title||'未命名公告';const meta=document.createElement('p');meta.textContent=`${record.category||'公告'}・${dateInput(record.publishedAt)}`;text.append(title,meta);const badges=document.createElement('div');badges.className='admin-badges';if(record.pinned){const pinned=document.createElement('span');pinned.className='badge';pinned.textContent='置頂';badges.append(pinned)}const state=document.createElement('span');state.className=`badge ${record.published?'live':'draft'}`;state.textContent=record.published?'已發布':'草稿';badges.append(state);item.append(text,badges);item.addEventListener('click',()=>fillForm(record));item.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fillForm(record)}});list.append(item)})}
async function refresh(){list.innerHTML='<p class="muted">讀取中…</p>';try{const snapshot=await getDocs(collection(db,'announcements'));records=snapshot.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||toDate(b.publishedAt)-toDate(a.publishedAt));renderList()}catch(error){console.error(error);list.innerHTML='<p class="status error">公告讀取失敗，請確認 Firestore 規則。</p>'}}

loginForm.addEventListener('submit',async event=>{event.preventDefault();setStatus(loginStatus,'登入中…');try{await setPersistence(auth,browserSessionPersistence);const result=await signInWithEmailAndPassword(auth,$('#loginEmail').value.trim(),$('#loginPassword').value);if(result.user.uid!==adminUid){await signOut(auth);throw new Error('這個帳號沒有管理權限。')}loginForm.reset()}catch(error){console.error(error);const message=error.code==='auth/invalid-credential'?'Email 或密碼錯誤。':error.message;setStatus(loginStatus,message,'error')}});
$('#logoutBtn').addEventListener('click',()=>signOut(auth));$('#resetBtn').addEventListener('click',resetForm);$('#refreshBtn').addEventListener('click',refresh);
form.addEventListener('submit',async event=>{event.preventDefault();setStatus(formStatus,'儲存中…');try{const id=$('#docId').value;const payload={category:$('#category').value,title:$('#title').value.trim(),excerpt:$('#excerpt').value.trim(),content:$('#content').value.trim(),images:validImages($('#images').value),published:$('#published').checked,pinned:$('#pinned').checked,publishedAt:Timestamp.fromDate(new Date(`${$('#publishedAt').value}T12:00:00`)),updatedAt:serverTimestamp()};if(!payload.title||!payload.content)throw new Error('請填寫公告標題與完整內容。');if(id){await updateDoc(doc(db,'announcements',id),payload)}else{payload.createdAt=serverTimestamp();await addDoc(collection(db,'announcements'),payload)}setStatus(formStatus,'公告已儲存。','success');resetForm();await refresh()}catch(error){console.error(error);setStatus(formStatus,error.message||'公告儲存失敗。','error')}});
$('#deleteBtn').addEventListener('click',async()=>{const id=$('#docId').value;if(!id)return;const record=records.find(item=>item.id===id);if(!confirm(`確定要刪除「${record?.title||'這篇公告'}」嗎？刪除後無法復原。`))return;setStatus(formStatus,'刪除中…');try{await deleteDoc(doc(db,'announcements',id));resetForm();await refresh()}catch(error){console.error(error);setStatus(formStatus,'刪除失敗，請稍後再試。','error')}});

onAuthStateChanged(auth,async user=>{if(user&&user.uid===adminUid){loginView.hidden=true;adminView.hidden=false;$('#adminEmail').textContent=user.email||'';resetForm();await refresh()}else{if(user)await signOut(auth);adminView.hidden=true;loginView.hidden=false;setStatus(loginStatus,'')}});
