import { browserSessionPersistence, onAuthStateChanged, setPersistence, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, serverTimestamp, setDoc, Timestamp, updateDoc } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import { auth, db } from "./firebase-client.js";
import { adminUid } from "./firebase-config.js";
import { defaultGuideContent, defaultSiteButtons, guideContentOrder, mergeGuideContent, mergeSiteButtons, siteButtonSections } from "./site-settings.js";

const $=selector=>document.querySelector(selector);
const loginView=$('#loginView'),adminView=$('#adminView'),loginForm=$('#loginForm'),form=$('#announcementForm');
const loginStatus=$('#loginStatus'),formStatus=$('#formStatus'),list=$('#announcementList');
const siteSettingsForm=$('#siteSettingsForm'),settingsFields=$('#siteSettingsFields'),settingsStatus=$('#settingsStatus');
const guideContentForm=$('#guideContentForm'),guideContentSelect=$('#guideContentSelect'),guideContentStatus=$('#guideContentStatus'),guideEntryList=$('#guideEntryList');
let records=[];
let guideContentState=mergeGuideContent();

function setStatus(element,message,type=''){element.textContent=message;element.className=`status ${type}`.trim()}
function toDate(value){if(value?.toDate)return value.toDate();const d=new Date(value);return Number.isNaN(d.getTime())?new Date(0):d}
function dateInput(value){const d=toDate(value);if(!d.getTime())return new Date().toISOString().slice(0,10);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function validImages(value,subject='每篇公告'){const lines=value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(lines.length>10)throw new Error(`${subject}最多可放 10 張圖片。`);for(const line of lines){let url;try{url=new URL(line)}catch{throw new Error(`圖片網址格式錯誤：${line}`)}if(!['http:','https:'].includes(url.protocol))throw new Error('圖片網址必須使用 http:// 或 https://。')}return lines}
function validButtonUrl(value){const url=value.trim();if(!url||url==='#')return '#';if(url.startsWith('#'))return url;try{const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw new Error()}catch{throw new Error(`網址格式錯誤：${url}（請使用 https:// 開頭）`)}return url}
function renderSettingsFields(buttons=defaultSiteButtons){settingsFields.innerHTML=siteButtonSections.map(section=>`<section class="settings-group"><h3>${section.title}</h3><div class="settings-fields">${section.keys.map(key=>{const item=buttons[key]||defaultSiteButtons[key];return `<article class="setting-item"><h4>${defaultSiteButtons[key].label}</h4><label>顯示名稱<input type="text" maxlength="40" required data-setting-label="${key}" value="${item.label.replaceAll('&','&amp;').replaceAll('"','&quot;')}"></label><label>前往網址<input type="text" inputmode="url" data-setting-url="${key}" value="${(item.url||'#').replaceAll('&','&amp;').replaceAll('"','&quot;')}" placeholder="https://..."></label></article>`}).join('')}</div></section>`).join('')}
function guideItems(){return guideContentState[guideContentSelect.value]?.items||[]}
function resetGuideForm(){guideContentForm.reset();$('#guideItemId').value='';$('#guideFormTitle').textContent='新增內容';$('#deleteGuideItemBtn').hidden=true;setStatus(guideContentStatus,'')}
function fillGuideContentForm(item){if(!item){resetGuideForm();return}$('#guideItemId').value=item.id;$('#guideContentTitle').value=item.title||'';$('#guideContentIntro').value=item.intro||'';$('#guideContentBody').value=item.content||'';$('#guideContentImages').value=(item.images||[]).join('\n');$('#guideFormTitle').textContent='編輯內容';$('#deleteGuideItemBtn').hidden=false;setStatus(guideContentStatus,'')}
function renderGuideEntryList(){const items=guideItems();if(!items.length){guideEntryList.innerHTML='<p class="muted">這個分類尚無內容，請按「新增內容」。</p>';return}guideEntryList.innerHTML='';items.forEach((item,index)=>{const button=document.createElement('button');button.type='button';button.className='guide-entry-list-item';button.dataset.guideItemId=item.id;const title=document.createElement('strong');title.textContent=item.title||`未命名內容 ${index+1}`;const intro=document.createElement('span');intro.textContent=item.intro||'尚未填寫簡介';button.append(title,intro);button.addEventListener('click',()=>{guideEntryList.querySelectorAll('.active').forEach(el=>el.classList.remove('active'));button.classList.add('active');fillGuideContentForm(item)});guideEntryList.append(button)})}
function selectGuideCategory(){renderGuideEntryList();const first=guideItems()[0];if(first){fillGuideContentForm(first);guideEntryList.querySelector('[data-guide-item-id]')?.classList.add('active')}else resetGuideForm()}
function initializeGuideContentEditor(){guideContentSelect.innerHTML=guideContentOrder.map(key=>`<option value="${key}">${defaultGuideContent[key].title}</option>`).join('');selectGuideCategory()}
async function loadSiteSettings(){setStatus(settingsStatus,'讀取網站設定中…');try{const snapshot=await getDoc(doc(db,'siteSettings','main'));const data=snapshot.exists()?snapshot.data():{};renderSettingsFields(mergeSiteButtons(data.buttons));guideContentState=mergeGuideContent(data.guides);initializeGuideContentEditor();setStatus(settingsStatus,'')}catch(error){console.error(error);renderSettingsFields();guideContentState=mergeGuideContent();initializeGuideContentEditor();setStatus(settingsStatus,'網站設定讀取失敗，請確認 Firestore 規則已更新。','error')}}
function resetForm(){form.reset();$('#docId').value='';$('#publishedAt').value=new Date().toISOString().slice(0,10);$('#formTitle').textContent='新增公告';$('#deleteBtn').hidden=true;setStatus(formStatus,'')}
function fillForm(record){$('#docId').value=record.id;$('#category').value=record.category||'公告';$('#publishedAt').value=dateInput(record.publishedAt);$('#title').value=record.title||'';$('#excerpt').value=record.excerpt||'';$('#content').value=record.content||'';$('#images').value=(record.images||[]).join('\n');$('#published').checked=Boolean(record.published);$('#pinned').checked=Boolean(record.pinned);$('#formTitle').textContent='編輯公告';$('#deleteBtn').hidden=false;setStatus(formStatus,'');scrollTo({top:0,behavior:'smooth'})}
function renderList(){if(!records.length){list.innerHTML='<p class="muted">尚無公告，請從左側新增第一篇。</p>';return}list.innerHTML='';records.forEach(record=>{const item=document.createElement('article');item.className='admin-item';item.tabIndex=0;const text=document.createElement('div');const title=document.createElement('h3');title.textContent=record.title||'未命名公告';const meta=document.createElement('p');meta.textContent=`${record.category||'公告'}・${dateInput(record.publishedAt)}`;text.append(title,meta);const badges=document.createElement('div');badges.className='admin-badges';if(record.pinned){const pinned=document.createElement('span');pinned.className='badge';pinned.textContent='置頂';badges.append(pinned)}const state=document.createElement('span');state.className=`badge ${record.published?'live':'draft'}`;state.textContent=record.published?'已發布':'草稿';badges.append(state);item.append(text,badges);item.addEventListener('click',()=>fillForm(record));item.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fillForm(record)}});list.append(item)})}
async function refresh(){list.innerHTML='<p class="muted">讀取中…</p>';try{const snapshot=await getDocs(collection(db,'announcements'));records=snapshot.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||toDate(b.publishedAt)-toDate(a.publishedAt));renderList()}catch(error){console.error(error);list.innerHTML='<p class="status error">公告讀取失敗，請確認 Firestore 規則。</p>'}}

loginForm.addEventListener('submit',async event=>{event.preventDefault();setStatus(loginStatus,'登入中…');try{await setPersistence(auth,browserSessionPersistence);const result=await signInWithEmailAndPassword(auth,$('#loginEmail').value.trim(),$('#loginPassword').value);if(result.user.uid!==adminUid){await signOut(auth);throw new Error('這個帳號沒有管理權限。')}loginForm.reset()}catch(error){console.error(error);const message=error.code==='auth/invalid-credential'?'Email 或密碼錯誤。':error.message;setStatus(loginStatus,message,'error')}});
$('#logoutBtn').addEventListener('click',()=>signOut(auth));$('#resetBtn').addEventListener('click',resetForm);$('#refreshBtn').addEventListener('click',refresh);
siteSettingsForm.addEventListener('submit',async event=>{event.preventDefault();setStatus(settingsStatus,'儲存網站設定中…');try{const buttons={};for(const key of Object.keys(defaultSiteButtons)){const label=$(`[data-setting-label="${key}"]`).value.trim();if(!label)throw new Error('顯示名稱不可空白。');buttons[key]={label,url:validButtonUrl($(`[data-setting-url="${key}"]`).value)}}await setDoc(doc(db,'siteSettings','main'),{buttons,updatedAt:serverTimestamp()},{merge:true});setStatus(settingsStatus,'網站設定已儲存，回到首頁重新整理即可看到更新。','success')}catch(error){console.error(error);setStatus(settingsStatus,error.message||'網站設定儲存失敗。','error')}});
guideContentSelect.addEventListener('change',selectGuideCategory);
$('#newGuideItemBtn').addEventListener('click',()=>{guideEntryList.querySelectorAll('.active').forEach(el=>el.classList.remove('active'));resetGuideForm();$('#guideContentTitle').focus()});
guideContentForm.addEventListener('submit',async event=>{event.preventDefault();setStatus(guideContentStatus,'儲存介紹內容中…');try{const key=guideContentSelect.value;const id=$('#guideItemId').value||`guide-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const payload={id,title:$('#guideContentTitle').value.trim(),intro:$('#guideContentIntro').value.trim(),content:$('#guideContentBody').value.trim(),images:validImages($('#guideContentImages').value,'每篇介紹內容')};if(!payload.title||!payload.intro||!payload.content)throw new Error('請填寫內容標題、簡短介紹與完整文字內容。');const items=guideItems();const existingIndex=items.findIndex(item=>item.id===id);if(existingIndex>=0)items[existingIndex]=payload;else items.push(payload);guideContentState[key]={items};await setDoc(doc(db,'siteSettings','main'),{guides:guideContentState,updatedAt:serverTimestamp()},{merge:true});renderGuideEntryList();fillGuideContentForm(payload);guideEntryList.querySelector(`[data-guide-item-id="${CSS.escape(id)}"]`)?.classList.add('active');setStatus(guideContentStatus,'這篇介紹內容已儲存，回到首頁重新整理即可看到更新。','success')}catch(error){console.error(error);setStatus(guideContentStatus,error.message||'介紹內容儲存失敗。','error')}});
$('#deleteGuideItemBtn').addEventListener('click',async()=>{const key=guideContentSelect.value,id=$('#guideItemId').value;if(!id)return;const item=guideItems().find(entry=>entry.id===id);if(!confirm(`確定要刪除「${item?.title||'這篇內容'}」嗎？刪除後無法復原。`))return;setStatus(guideContentStatus,'刪除中…');try{guideContentState[key]={items:guideItems().filter(entry=>entry.id!==id)};await setDoc(doc(db,'siteSettings','main'),{guides:guideContentState,updatedAt:serverTimestamp()},{merge:true});selectGuideCategory();setStatus(guideContentStatus,'這篇介紹內容已刪除。','success')}catch(error){console.error(error);setStatus(guideContentStatus,'刪除失敗，請稍後再試。','error')}});
form.addEventListener('submit',async event=>{event.preventDefault();setStatus(formStatus,'儲存中…');try{const id=$('#docId').value;const payload={category:$('#category').value,title:$('#title').value.trim(),excerpt:$('#excerpt').value.trim(),content:$('#content').value.trim(),images:validImages($('#images').value),published:$('#published').checked,pinned:$('#pinned').checked,publishedAt:Timestamp.fromDate(new Date(`${$('#publishedAt').value}T12:00:00`)),updatedAt:serverTimestamp()};if(!payload.title||!payload.content)throw new Error('請填寫公告標題與完整內容。');if(id){await updateDoc(doc(db,'announcements',id),payload)}else{payload.createdAt=serverTimestamp();await addDoc(collection(db,'announcements'),payload)}setStatus(formStatus,'公告已儲存。','success');resetForm();await refresh()}catch(error){console.error(error);setStatus(formStatus,error.message||'公告儲存失敗。','error')}});
$('#deleteBtn').addEventListener('click',async()=>{const id=$('#docId').value;if(!id)return;const record=records.find(item=>item.id===id);if(!confirm(`確定要刪除「${record?.title||'這篇公告'}」嗎？刪除後無法復原。`))return;setStatus(formStatus,'刪除中…');try{await deleteDoc(doc(db,'announcements',id));resetForm();await refresh()}catch(error){console.error(error);setStatus(formStatus,'刪除失敗，請稍後再試。','error')}});

onAuthStateChanged(auth,async user=>{if(user&&user.uid===adminUid){loginView.hidden=true;adminView.hidden=false;$('#adminEmail').textContent=user.email||'';resetForm();await Promise.all([refresh(),loadSiteSettings()])}else{if(user)await signOut(auth);adminView.hidden=true;loginView.hidden=false;setStatus(loginStatus,'')}});
